### DISCUSSION TITLE
API Security Key does not enable

### DISCUSSION THREAD

**Discussion by OweysMomenzada** [qdrant/qdrant#2429] [Q&A] [answered]
For the purpose of building a Qdrant DB with docker-compose I want to use bathic auth.

I followed this website:
https://qdrant.tech/documentation/guides/security/

For this I defined my docker-compose file as follows:
```
version: '3.4'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    env_file:
      - .env
    volumes:
      - ./config.yml:/etc/qdrant/config.yml
```

Further the config.yml was defined as:
```
service:
  api_key: ${QDRANT_API_KEY}
```

However, the endpoints are still unprotected and I can still write and read items. Is there any suggestions?
