### DISCUSSION TITLE
Error in deployment on Redhat Openshift

### DISCUSSION THREAD

**Discussion by edwardspaulg** [qdrant/qdrant#2868] [Q&A]
Hi 
Looking for help in where to look for further information to resolve this error when Qdrant starts up in a pod:

Panic occurred in file lib/storage/src/content_manager/toc/mod.rs at line 88: Can't create Snapshots directory: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

I am delploying in a Redhat Openshift K8S cluster. I am creating a persistent volume claim then mounting it  

          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc

The pvc is good, but seems like i need additional permissions, but not sure what else it needs.

**Comment by thesteve0** [comment]
Have you tried using the unprivileged containers

https://hub.docker.com/layers/qdrant/qdrant/v1.6.1-unprivileged/images/sha256-fb2ef5a7b1d33649a8875446fd3dad806741d9deddffbb5901d99881725698e8?context=explore

**Reply by edwardspaulg** [reply]
Just tried that qdrant:v1.6.1-unprivileged image and still receive the same error at statup

**Comment by luizerico** [comment]
Just map the /qdrant/snapshots to a PVC. It worked for me.
```
   spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: qdrant-data
        - name: snapshots
          persistentVolumeClaim:
            claimName: qdrant-snapshots
...
          volumeMounts:
            - name: data
              mountPath: /qdrant/storage
            - name: snapshots
              mountPath: /qdrant/snapshots
```
