### DISCUSSION TITLE
Qdrant on Kubernetes OOMKilled During Ingestion

### DISCUSSION THREAD

**Discussion by dacox** [qdrant/qdrant#3501] [Q&A]
We are running on Kubernetes. Each node has 4 cpu and 12.97GB of allocatable memory.

We are running an 8 replica cluster.

We have tried many different memory requests and limits, and _always_ experience OOMKills at some point during ingestion.

Looking at charts, memory ramps until our requested amount, and then we experience OOMKills.

<img width="1220" alt="Screenshot 2024-01-31 at 8 21 36 AM" src="https://github.com/qdrant/qdrant/assets/3887682/e45a2c70-34cd-405e-9adb-6551ccd05da1">

Here are messages from `dmesg`

```
[45677.453474] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=ff638e2d2993902ea12313da1e88275f869fcb15c0a1eac8861416f12183438b,mems_allowed=0,oom_memcg=/kubepods/burstable/pod18bd39a7-6b6a-4570-96b5-52c07ee28159/ff638e2d2993902ea12313da1e88275f869fcb15c0a1eac8861416f12183438b,task_memcg=/kubepods/burstable/pod18bd39a7-6b6a-4570-96b5-52c07ee28159/ff638e2d2993902ea12313da1e88275f869fcb15c0a1eac8861416f12183438b,task=qdrant,pid=935981,uid=0
[45677.493439] Memory cgroup out of memory: Killed process 935981 (qdrant) total-vm:17866828kB, anon-rss:11191516kB, file-rss:24528kB, shmem-rss:0kB, UID:0 pgtables:25772kB oom_score_adj:301
[46011.557401] [ 944050]     0 944050  4441105  2803815 26427392        0           301 qdrant
[46011.565900] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=2dcb9b2e6640d719e580546826d65e79ef1dcc4106728893b56073255d09c36e,mems_allowed=0,oom_memcg=/kubepods/burstable/pod18bd39a7-6b6a-4570-96b5-52c07ee28159/2dcb9b2e6640d719e580546826d65e79ef1dcc4106728893b56073255d09c36e,task_memcg=/kubepods/burstable/pod18bd39a7-6b6a-4570-96b5-52c07ee28159/2dcb9b2e6640d719e580546826d65e79ef1dcc4106728893b56073255d09c36e,task=qdrant,pid=944050,uid=0
[46011.605838] Memory cgroup out of memory: Killed process 944050 (qdrant) total-vm:17764420kB, anon-rss:11190680kB, file-rss:24580kB, shmem-rss:0kB, UID:0 pgtables:25808kB oom_score_adj:301
```

Our full collection is 65 million 1536 dim vectors.

This is very frustrating, My napkin math says we have plenty of RAM for binary quantization - i feel in my gut this has to do with memmap.

When the cluster goes down, it has problems booting from disk again, as it seems to be using tons of virtual memory and getting OOMKIlled.

At a loss for what to do. 

Here is our collection config:

```
PUT /collections/media_embeddings_c927
{
  "vectors": {
    "size": 1536,
    "distance": "Cosine",
  },
  "optimizers_config": {
    "default_segment_number": 32,
    "memmap_threshold": 10000,
    "indexing_threshold": 0
  },
  "hnsw_config": {
    "on_disk": true
  },
  "quantization_config": {
    "binary": {
      "always_ram": true
    }
  },
  "shard_number": 8,
  "replication_factor": 2
}
```

Here is our `StatefulSet`

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  labels:
    app: qdrant
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant
    app.kubernetes.io/version: "v1.7.2"
spec:
  replicas: 8
  selector:
    matchLabels:
      app: qdrant
      app.kubernetes.io/name: qdrant
      app.kubernetes.io/instance: qdrant
  serviceName: qdrant-headless
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '6333'
        prometheus.io/name: '/metrics'
        sidecar.istio.io/rewriteAppHTTPProbers: 'false'
      labels:
        app: qdrant
        app.kubernetes.io/name: qdrant
        app.kubernetes.io/instance: qdrant
    spec:
      containers:
        - name: qdrant
          image: "qdrant/qdrant:v1.7.2"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
          - ./config/initialize.sh
          ports:
            - name: http
              containerPort: 6333
              protocol: TCP
            - name: grpc
              containerPort: 6334
              protocol: TCP
            - name: p2p
              containerPort: 6335
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 6333
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 6333
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /
              port: 6333
            initialDelaySeconds: 600
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          resources:
            limits:
              cpu: "4"
              memory: 11900M
            requests:
              cpu: "3"
              memory: 11900M
          volumeMounts:
          - name: qdrant-storage
            mountPath: /qdrant/storage
          - name: qdrant-config
            mountPath: /qdrant/config/initialize.sh
            subPath: initialize.sh
          - name: qdrant-config
            mountPath: /qdrant/config/production.yaml
            subPath: production.yaml
      volumes:
        - name: qdrant-config
          configMap:
            name: qdrant
            defaultMode: 0755

  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
        labels:
          app: qdrant
      spec:
        storageClassName: ssd  
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "500Gi"
 ```
 
 There is also an injected `istio-proxy` pod with memory requests and limits of `128Mi` and `1Gi`
