### DISCUSSION TITLE
Enable TLS for internal cluster and external client

### DISCUSSION THREAD

**Discussion by navneetrajput06** [qdrant/qdrant#3553] [Q&A]
Hi Team,
We are trying to enable TLS for external and internal communication in our qdrant cluster which is deployed in distributed mode.
While trying to deploy the cluster my pods are not starting with below error.

2024-02-06T18:40:17.596938Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json    
Error: No such file or directory (os error 2)

We are using help to deploy and below is the values.yaml
# TLS configuration.
# Required if either service.enable_tls or cluster.p2p.enable_tls is true.
tls:
  # Server certificate chain file
  cert: /localpath/cert.pem
  key: /localpath/key.pem
  ca_cert: /localpath/cacert.pem
config:
  cluster:
    enabled: true
    p2p:
      enable_tls: true
      port: 6335

please help me if i am missing anything and also let us know how we can connect to qdrant cluster using python (configuration parameters to pass the certificate files)

**Comment by navneetrajput06** [comment]
<img width="770" alt="Screenshot 2024-02-06 at 4 01 16 PM" src="https://github.com/qdrant/qdrant/assets/144489426/11159038-5d64-4be5-b042-3e02f02d0016">

**Comment by timvisee** [comment]
```
2024-02-06T18:40:17.596938Z INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json
Error: No such file or directory (os error 2)
```

This error is not related to your TLS configuration.

Could you describe how you start your nodes? Are you doing it t he same way as we describe qdrant.tech/documentation/guides/distributed_deployment?

It is important to set correct `--uri` and `--bootstrap` parameters. Also, your storage must not be lost across container restarts. So, `storage/raft_state.json` should survive container restarts.

**Reply by navneetrajput06** [reply]
This is happening only when i am saying enable_tls= true in config.cluster.p2p for internal tls. This is Kubernetes cluster. 
and also i dint see any solution to copy our custom certificates at the time of deployment using helm.

could you please tell me exact configuration steps using helm to enable tls fir client as well as p2p.

**Reply by lifeiswilde** [reply]
Hi there!

Running into a similar issue when tls is enabled for internal and external.

This is my values.yaml, [merges with upstream](https://github.com/qdrant/qdrant-helm/blob/main/charts/qdrant/values.yaml)

```yaml
replicaCount: 3

image:
  tag: "1.13.4"

persistence:
  size: 200Gi

env:
- name: QDRANT_TLS_SERVER_CERT
  value: "/qdrant/tls/tls.crt"
- name: QDRANT_TLS_SERVER_KEY
  value: "/qdrant/tls/tls.key"
- name: QDRANT_TLS_CA_CERT
  value: "/qdrant/tls/ca.crt"

config:
  cluster:
    enabled: true
    p2p:
      port: 6335
      url_scheme: "https" 
      enable_tls: true
      tls:
        cert_path: "/qdrant/tls/tls.crt"
        key_path: "/qdrant/tls/tls.key"
        ca_cert_path: "/qdrant/tls/ca.crt"
    consensus:
      tick_period_ms: 100
  service:
    enable_tls: true
    api:
      http:
        tls:
          server_cert: "/qdrant/tls/tls.crt"
          server_key: "/qdrant/tls/tls.key"
          ca_cert: "/qdrant/tls/ca.crt"
      grpc:
        tls:
          server_cert: "/qdrant/tls/tls.crt"
          server_key: "/qdrant/tls/tls.key"
          ca_cert: "/qdrant/tls/ca.crt"

additionalVolumes:
- name: tls-certs
  secret:
    secretName: tls

additionalVolumeMounts:
- name: tls-certs
  mountPath: "/qdrant/tls"
  readOnly: true

updateVolumeFsOwnership: false # New deployment so we shouldn't need this?
```

On a fresh deploy (no remaining resources, including pvcs)

```bash
kubectl logs -n qdrant qdrant-0
Starting initializing for pod 0
           _                 _
  __ _  __| |_ __ __ _ _ __ | |_
 / _` |/ _` | '__/ _` | '_ \| __|
| (_| | (_| | | | (_| | | | | |_
 \__, |\__,_|_|  \__,_|_| |_|\__|
    |_|

Version: 1.13.4, build: 7abc6843
Access web UI at https://localhost:6333/dashboard

2025-03-06T00:03:20.166761Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json
Error: No such file or directory (os error 2)
```
