### ISSUE TITLE
User Authorization so random people cannot drop an entire collection

### ISSUE THREAD

**Issue by junwang-wish** [qdrant/qdrant#1683]
Based on my understanding of https://qdrant.tech/documentation/administration/ , let's say I deploy qdrant to http:some_ip:some_port , currently there is not a way to prevent random people having access to http:some_ip:some_port dropping an entire collection. This could happen inside orgs where some users accidentally cause production outage.

Is there plan to add user authorization (or if I missed it in the doc, is there a way to enable authorization already) ?

**Comment by generall** [comment]
Hi @junwang-wish, the Api-key based authentication is available on the cloud.

There are also a couple of tutorials from our community members:

- https://bichuetti.net/qdrant-authentication
- https://medium.com/@stephane.busso/setting-up-qdrant-with-kong-for-authentication-a-step-by-step-guide-91c206a913f8

We have also plans to introduce simple authentication directly into qdrant and more sophisticated, role-based access control into the on-prem enterprise cluster manager.

**Comment by bbedward** [comment]
We have an example with docker compose and nginx basic auth proxy

https://github.com/stablecog/sc-qdrant

But basic auth doesn’t work for the grpc api, only the rest one.

**Comment by DengYiping** [comment]
I've added TLS based auth here: 
https://github.com/qdrant/qdrant/pull/1663

There is no endpoint level auth yet, but that can be achieved using a nginx reverse proxy.

**Comment by JonGerrand** [comment]
For anyone following the route of using Kong for key-auth management, the following can be used to create a containerised form of `qdrant` with API key-based authentication: 

docker-compose.yml:
```yaml
version: '3.5'

services:
  kong:
    container_name: kong
    image: kong:3.2.2
    volumes:
      - ${PWD}:/kong/declarative/
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
    restart: always
    networks:
      - kong-net

  qdrant:
    depends_on:
      kong:
        condition: service_healthy
    container_name: qdrant
    image: qdrant/qdrant:latest
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/qdrant:/qdrant/storage
      - ${PWD}/config.yaml:/qdrant/config/production.yaml
    ports:
      - "6333:6333"
    restart: always
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
``` 
and the config file: 

kong.yml
```yaml
# Demo Kong config file.
# <api-key> should be replaced by a strong key

_format_version: "3.0"
_transform: true

services:
- host: qdrant
  name: qdrant
  port: 6333
  protocol: http
  routes:
  - name: qdrant_route
    paths:
    - /
    strip_path: true

consumers:
- username: qdrant

keyauth_credentials:
- consumer: qdrant
  key: <api-key>

plugins:
- name: key-auth
  config:
    key_in_header: true
    key_names:
    - api-key 
```

You can then connect via: 
```python
import qdrant_client 

url = <localhost for testing purposes>
api_key = <your-defined-api-key>
client = qdrant_client.QdrantClient(url=url,
                                    port=8000,
                                    api_key=api_key)
```
