### ISSUE TITLE
Docker Secrets Compability for sensitive ENVs

### ISSUE THREAD

**Issue by prononext** [qdrant/qdrant#2341]
### Description

It would be really nice to have the possibility to use Docker Secrets on the following ENV. The ENVs should support the _FILE suffix to get it working like this:

        - QDRANT__SERVICE__API_KEY_FILE

So you can use the docker stack in a more save manner and create the docker secrets before you run the stack in a excrypted manner https://docs.docker.com/engine/reference/commandline/secret_create/

```
version: '3.9'

services:

 qdrant: 
    image: docker.io/qdrant/qdrant:v1.3.2
    secrets:
      - QDRANT_API_KEY    
    environment:
        - TZ=Etc/UTC
        - RUN_MODE=production
        - QDRANT__SERVICE__HTTP_PORT=6333
        - QDRANT__SERVICE__API_KEY_FILE=/run/secrets/QDRANT_API_KEY
        - QDRANT__TELEMETRY_DISABLED=true
    ports:
        - '6333:6333'
    volumes:
      - qdrant_data:/qdrant/storage        

volumes:
  qdrant_data:

secrets:
  QDRANT_API_KEY:
    name: QDRANT_API_KEY
    external: true
```
