### ISSUE TITLE
Tweaks on gituhbactions

### ISSUE THREAD

**Issue by zodman** [qdrant/qdrant#2377]
You can save more time on `integration-testing`

On the integration-test workflow:

all the jobs test-* have the task `cargo build `, I think you can save more time create a job called build and create others jobs depends of it.

```
jobs:
   build:
          runs-on: ubuntu-latest
		  steps:
		    - name: Install minimal stable
		      uses: dtolnay/rust-toolchain@stable 
		    - uses: actions/checkout@v3
		    - uses: Swatinem/rust-cache@v2
		    - name: Install Protoc
		      uses: arduino/setup-protoc@v1
		      with:
		        repo-token: ${{ secrets.GITHUB_TOKEN }}
		    - name: Build
		      run: cargo build --features service_debug
	test:
          runs-on: ubuntu-latest
          # this jobs will not start after build finished
          needs: build
       	  steps:
       	     ....

```

this create jobs dependencies the build will be reused by others ...

```
build
   |_ test
```
