### ISSUE TITLE
Unable to Access Qdrant APIs via HTTPS in EKS with ALB Ingress

### ISSUE THREAD

**Issue by Abdullah-neurocareAI** [qdrant/qdrant#3425]
### **Problem Overview:**
I have deployed Qdrant on Amazon Elastic Kubernetes Service (EKS) using a StatefulSet. The deployment utilizes the Application Load Balancer (ALB) Ingress Controller for secure HTTPS access with AWS Certificate Manager (ACM) Amazon Resource Name (ARN). While successful in accessing the Qdrant database UI over HTTPS, I am encountering challenges when attempting to access Qdrant APIs through the Qdrant-client.

I use the following line of code to establish a connection with the database:

```
qdrant = QdrantClient(url=qdrant_url, api_key=qdrant_api_key, port=6333)
```

However, every attempt to interact with the database, whether creating a collection, uploading data, or retrieving the number of collections, results in a timeout error. The deployment details are provided below, and **any assistance in resolving this matter would be greatly appreciated.**

### **Deployment Details:**

- Qdrant deployed using StatefulSet.
- ALB Ingress Controller utilized with ACM ARN for HTTPS.
- Secret created to mount cert.pem and key.pem into the Qdrant container.

### **Configuration:**

Enabled TLS under the service section in the cluster configuration.

### **Observations:**

- Successful access to Qdrant UI via HTTPS without issues.
- Challenges encountered when accessing Qdrant APIs over HTTPS.
- Certificates and keys provided correctly during the deployment.

### **Steps to Reproduce:**

- Deploy Qdrant on EKS with StatefulSet.
- Configure ALB Ingress with ACM ARN for HTTPS.
- Attempt to access Qdrant APIs over HTTPS.

### **Cluster Config:**
 
```
service:

  enable_tls: true
tls:
  cert: ./tls/cert.pem
  key: ./tls/key.pem
```

### **Volume**
```
additionalVolumes:
  - name: tls-secret
    secret:
      secretName: tls-secret-name
additionalVolumeMounts:
  - name: tls-secret
    mountPath: ./qdrant/tls
```

### **Ingress** config:
```
ingress:
  enabled: true
  ingressClassName: ""
  additionalLabels: {}
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/subnets: subnet-xxx,subnet-xxx,subnet-xxx
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xxx:xxx:certificate/xxx
```
