### ISSUE TITLE
Add curl to docker image to configure Healthchecks

### ISSUE THREAD

**Issue by fedecompa** [qdrant/qdrant#3491]
Install curl in the docker image to configure Healthchecks

**Comment by timvisee** [comment]
Could you elaborate on how adding curl would help with this? What would the final health checking approach look like?

**Comment by fedecompa** [comment]
Hi! For example to do something like this in the docker-compose:

healthcheck:
  test: curl -s http://localhost:6333/healthz | grep -q 'healthz check passed' || exit 1
  interval: 30s
  retries: 20
  start_period: 30s

**Comment by timvisee** [comment]
I wasn't aware that Docker Compose can't simply probe an URL but requires a command.

What about wrapping your own image around it to add `curl`?

If you have a recent docker-compose version, you may use an inline docker file like:

```yaml
services:
  qdrant:
    build:
      context: .
      dockerfile_inline: |
        FROM qdrant/qdrant:latest
        RUN apt-get update -yq && apt-get install -yqq curl
    healthcheck:
      test: curl -s http://localhost:6333/healthz | grep -q 'healthz check passed' || exit 1
      interval: 30s
      retries: 20
      start_period: 30s
```

If it does not support inline files you can do it like this:

```yaml
services:
  qdrant:
    build:
      context: .
      dockerfile: qdrant.Dockerfile
    healthcheck:
      test: curl -s http://localhost:6333/healthz | grep -q 'healthz check passed' || exit 1
      interval: 30s
      retries: 20
      start_period: 30s
```

and then create a `qdrant.Dockerfile` file alongside it:

```Dockerfile
FROM qdrant/qdrant:latest

RUN apt-get update -yq && apt-get install -yqq curl
```

**Comment by fedecompa** [comment]
Yes, but in this way every time I install the container I need to rebuild the image and exit to the internet to download packages at runtime. Docker images of other database like mongodb or elasticsearch have the curl (or wget or ping) command already installed to configure better healthchecks.

**Comment by timvisee** [comment]
Yes, I understand that it wouldn't be optimal.

Regarding `curl` in the container, I have no objection against this.

I've opened this PR: https://github.com/qdrant/qdrant/pull/3505

**Comment by fedecompa** [comment]
Thanks!

**Comment by ffuugoo** [comment]
Why not just pull [curl docker image] and use it for health checks? Sure, you'll have to pull two images instead of one, but I don't see how it's different from pulling Qdrant docker image. And if you use a separate container, once you pulled it the first time, you don't need to rebuild (or even pull) anything when you upgrade Qdrant container.

[curl docker image]: https://hub.docker.com/r/curlimages/curl

**Comment by bashofmann** [comment]
I don't think this is a good idea from a security perspective. Adding more things that are not strictly needed for running Qdrant to the container image increases the potential attack surface.
I think we should actually move in the other direction and not include or remove stuff that is not necessary, like `apt`.

In case of adding curl it could make it a lot easier for an attacker to download additional scripts or binaries into the container or transport data out if they somehow got into the container because of another vulnerability.

I think @ffuugoo proposal is a very good option. An example compose file could look something like this:

```
services:
  qdrant:
    image: qdrant/qdrant:v1.7.3
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data
  healthcheck:
    restart: always 
    image: curlimages/curl:latest
    entrypoint: ["/bin/sh", "-c", "--", "while true; do sleep 30; done;"]
    depends_on:
      - qdrant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://qdrant:6333/readyz"]
      interval: 10s
      timeout: 2s
      retries: 5
```

Additionally, in a lot of production setup cases, you will likely put some kind of load balancer in front of Qdrant, which would do the health checks from the outside, or use an orchestrator like Kubernetes, which als checks from the outside and does not rely on any tools being present inside of the containers.
