### ISSUE TITLE
Implement S3 snapshot manager

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#4109]
**Is your feature request related to a problem? Please describe.**

Continuation of the issue https://github.com/qdrant/qdrant/issues/3324

In previous iterations we decomposed Snapshot manager into multiple  implementations, depending of the storage backend.

https://github.com/qdrant/qdrant/blob/61fa4e74e4de9f08393a77a14489983a32700c85/lib/collection/src/common/snapshots_manager.rs#L192

But `SnapshotStorageS3` is currently not implemented and not used.

**Describe the solution you'd like**

- Implement missing functions in `SnapshotStorageS3`
- Alter the settings, to allow explicitly select between local FS and S3
Example:

```yaml
storage:

  # Where to store snapshots
  snapshots_path: ./snapshots
  
  s3_config: 
    bucket: "s3://hello-world"
  
  snapshots_storage: "s3" | "local" # "local" - default
```

- Provide an integration test, which would run in CI and demonstrate that it is possible to create and recover from snapshot stored in s3 (deploy minio locally?) - similar to https://github.com/qdrant/qdrant/blob/3ad1528ebe04a45a4034f8f49d5458da01009487/tests/snapshots/snapshots-recovery.sh

**Describe alternatives you've considered**
-

**Additional context**

There are some notable previous attempts which might be helpful - https://github.com/qdrant/qdrant/pull/3430
