### ISSUE TITLE
Add a healthcheck command that can be used within docker compose

### ISSUE THREAD

**Issue by pkordes** [qdrant/qdrant#4250]
**Is your feature request related to a problem? Please describe.**
Currently cannot institute a healthcheck since curl, etc. requested previously were determined to be a security issue.

**Describe the solution you'd like**
Create some simple ootb command that can be executed on an interval from within container to decide when healthy.  By creating the command yourself, you can control security and exactly what it can/cannot do.

**Describe alternatives you've considered**
Anything checking the endpoint via a tool requires curl,wget,nc, etc that were determined to be security risks in a different ticket

**Additional context**
Without this, it is almost impossible to use the ootb healthcheck built into compose.

**Comment by generall** [comment]
related discussion here: https://github.com/qdrant/qdrant/issues/3491

**Comment by pkordes** [comment]
How often are these tickets dispositioned?

**Comment by NathanAP** [comment]
I also ran into this need today. It would be awesome to have a curl in compose to help us with this.

**Comment by rennokki** [comment]
Maybe like this? Original idea: https://github.com/dart-lang/dart-docker/issues/58#issuecomment-1086975460

```yaml
services:
  qdrant:
    # ...
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
```
