### ISSUE TITLE
3 node cluster cannot handle downtime of single node

### ISSUE THREAD

**Issue by bitfactory-sem-denbroeder** [qdrant/qdrant#4357]
I'm running a 3 node qdrant cluster in k8s, when rebooting a node for maintenance 1 of the 3 nodes has downtime and will not be scheduled. This causes qdrant to only give out 500 error codes until the 3rd pod is up and running again. 

## Steps to Reproduce
1. have a 3 node cluster
2. reboot 1 of the underlying k8s nodes

values.yaml are as follows:
```
replicaCount: 3
persistence:
        accessModes: ["ReadWriteOnce"]
        size: 300Gi
        storageClassName: disk-hdd

config:
  cluster:
    enabled: true
    p2p:
      port: 6335
    consensus:
      tick_period_ms: 100
```
## Expected Behavior
I'd expect the request to continue when only 1 of 3 is down.

I'm unsure if my config is not enough for a HA setup, if so I'd like some tips to make sure this works next maintenance window

## Error
`Service internal error: 1 of 1 read operations failed: Service internal error: Tonic status error: status: Unavailable, message: "Failed to connect to http://qdrant-dev-2.qdrant-dev-headless:6335/, error: transport error", details: [], metadata: MetadataMap { headers: {} }`

This is the exact error message im recieving.
