### ISSUE TITLE
OOM when trying to ingest large datasets due to caching

### ISSUE THREAD

**Issue by skeptrunedev** [qdrant/qdrant#4378]
When rapidly ingesting with quantization turned on, the full vectors seem to be put into the cache such that the cluster uses significantly more memory than one would expect. 

## Current Behavior

Caching causes premature OOM kills during ingest which then starts off a waiting game: 

1. OOM
2. Slow Restart
3. Start indexing again (manual trigger)
4. OOM after N period of time when cache builds up again
5. Slower Restart + Data Loss
....

## Steps to Reproduce

1. Stand up Qdrant cluster and create collection with a memory expectation based on quantization parameters 
2. Ingest points into collection 
3. Look at memory and realize it's higher than you expect because caching is going on 

![image](https://github.com/qdrant/qdrant/assets/15804464/7446a409-3504-41e1-b119-2c0c6b3830d5)

> Unused RAM is wasted RAM

😢 I over-provisioned to start so I wouldn't have to resize Kube nodes then restart Qdrant and wait for long load time into mem, but to do that I need Qdrant to let me have unused RAM. 

## Expected Behavior

Have the ability to prevent Qdrant from caching to the point of causing an OOM. 

1. Set a parameter on collection to set max for `cache` 

## Context (Environment)

We are trying to ingest 10M+ points on a Kube setup. We setup the cluster with nodes such that we are initially over provisioned because we assume we will at some point need all the memory allocated.

**Comment by skeptrunedev** [comment]
Complete configuration:

```
replicaCount: 4

image:
  repository: docker.io/qdrant/qdrant
  pullPolicy: IfNotPresent
  tag: ""
  useUnprivilegedImage: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
args: ["./config/initialize.sh"]
env: {}
  # - name: QDRANT_ALLOW_RECOVERY_MODE
  #   value: true

# checks - Readiness and liveness checks can only be enabled for either http (REST) or grpc (multiple checks not supported)
# grpc checks are only available from k8s 1.24+ so as of per default we check http
service:
  type: ClusterIP
  additionalLabels: {}
  annotations: {}
  loadBalancerIP: ""
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      protocol: TCP
      checksEnabled: true
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
      checksEnabled: false
    - name: p2p
      port: 6335
      targetPort: 6335
      protocol: TCP
      checksEnabled: false

ingress:
  enabled: true
  ingressClassName: ""
  additionalLabels: {}
  annotations: {}
    # kubernetes.io/ingress.class: alb
  hosts:
    - paths:
        - path: /
          pathType: Prefix
          servicePort: 6333
  tls: []
    # - hosts:
    #    - example-domain.com
    #   secretName: tls-secret-name

livenessProbe:
  enabled: false
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 6
  successThreshold: 1

startupProbe:
  enabled: false
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 30
  successThreshold: 1

additionalLabels: {}
podAnnotations: {}
podLabels: {}

resources:
  limits:
    cpu: 29440m
    memory: 200Gi
  requests:
    cpu: 29440m
    memory: 200Gi

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 2000
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true

podSecurityContext:
  fsGroup: 3000
  fsGroupChangePolicy: Always

# If true ensures that the pre-existing files on the storage and snapshot volume are owned by the container's
# user and fsGroup
updateVolumeFsOwnership: true

nodeSelector: {}

tolerations: 
- key: "qdrant-node"
  operator: "Exists"
  effect: "NoSchedule"


affinity: {}

topologySpreadConstraints: []

persistence:
  accessModes: ["ReadWriteOnce"]
  size: 200Gi
  annotations: {}
  # storageClassName: local-path

# only supported for single node qdrant clusters.
snapshotRestoration:
  enabled: false
  pvcName: snapshots-pvc
  snapshots:
  #  - /qdrant/snapshots/test_collection/test_collection-2022-10-24-13-56-50.snapshot:test_collection

# modification example for configuration to overwrite defaults
config:
  cluster:
    enabled: true
    p2p:
      port: 6335
    consensus:
      tick_period_ms: 100

sidecarContainers: []
# sidecarContainers:
#   - name: my-sidecar
#     image: qdrant/my-sidecar-image
#     imagePullPolicy: Always
#     ports:
#     - name: my-port
#       containerPort: 5000
#       protocol: TCP
#     resources:
#       requests:
#         memory: 10Mi
#         cpu: 10m
#       limits:
#         memory: 100Mi
#         cpu: 100m

metrics:
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    scrapeInterval: 30s
    scrapeTimeout: 10s
    targetPort: http
    targetPath: "/metrics"
    ## MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    metricRelabelings: []
    ## RelabelConfigs to apply to samples before scraping
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    ##
    relabelings: []

serviceAccount:
  annotations: {}

priorityClassName: ""

podManagementPolicy: Parallel

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
  # do not enable if you are using not in 1.27
  unhealthyPodEvictionPolicy: ""
  # minAvailable: 1

# api key for authentication at qdrant
# false: no api key will be configured
# true: an api key will be auto-generated
# string: the given string will be set as an apikey
apiKey: "ha_nice_try"
# read-only api key for authentication at qdrant
# false: no read-only api key will be configured
# true: an read-only api key will be auto-generated
# string: the given string will be set as a read-only apikey
readOnlyApiKey: false

additionalVolumes: []
# - name: volumeName
#   emptyDir: {}

additionalVolumeMounts: []
# - name: volumeName
#   mountPath: "/mount/path"

```
