### ISSUE TITLE
cpu usage is abnormal

### ISSUE THREAD

**Issue by kawhi-xl** [qdrant/qdrant#4446]
## Current Behavior

my qdrant cluster with 2 nodes. 
cluster config:
```yaml
cluster:
  # Use `enabled: true` to run Qdrant in distributed deployment mode
  enabled: true
  # Configuration of the inter-cluster communication
  p2p:
    # Port for internal communication between peers
    port: 6335

  # Configuration related to distributed consensus algorithm
  consensus:
    # How frequently peers should ping each other.
    # Setting this parameter to lower value will allow consensus
    # to detect disconnected node earlier, but too frequent
    # tick period may create significant network and CPU overhead.
    # We encourage you NOT to change this parameter unless you know what you are doing.
    tick_period_ms: 100
storage:
  performance:
    # Number of parallel threads used for search operations. If 0 - auto selection.
    max_search_threads: 0
service:
  grpc_port: 6334
```

the collection config:
```json
{
  "result": {
    "status": "green",
    "optimizer_status": "ok",
    "vectors_count": 11484,
    "indexed_vectors_count": 0,
    "points_count": 10458,
    "segments_count": 3,
    "config": {
      "params": {
        "vectors": {
          "size": 768,
          "distance": "Cosine",
          "on_disk": true
        },
        "shard_number": 2,
        "replication_factor": 1,
        "write_consistency_factor": 1,
        "on_disk_payload": true
      },
      "hnsw_config": {
        "m": 0,
        "ef_construct": 100,
        "full_scan_threshold": 10000,
        "max_indexing_threads": 0,
        "on_disk": true,
        "payload_m": 16
      },
      "optimizer_config": {
        "deleted_threshold": 0.2,
        "vacuum_min_vector_number": 1000,
        "default_segment_number": 2,
        "max_segment_size": null,
        "memmap_threshold": 20000,
        "indexing_threshold": 20000,
        "flush_interval_sec": 5,
        "max_optimization_threads": 1
      },
      "wal_config": {
        "wal_capacity_mb": 1024,
        "wal_segments_ahead": 0
      },
      "quantization_config": {
        "scalar": {
          "type": "int8",
          "quantile": 0.99,
          "always_ram": true
        }
      }
    },
    "payload_schema": {
      "shop_id": {
        "data_type": "keyword",
        "points": 10453
      }
    }
  },
  "status": "ok",
  "time": 0.000624154
}
```

app programer connected one of node ip with grpc. the business request rps about 100, but other node cpu is very high suddenly.  what happend?

![image](https://github.com/qdrant/qdrant/assets/41316350/ae1c394e-580a-4382-8442-003c4004a249)
