### ISSUE TITLE
Using multivector as query vector throws error

### ISSUE THREAD

**Issue by az-arteria** [qdrant/qdrant#4839]
## Current Behavior
When performing a search with a multivector as the query vector (like this example below), an error is thrown. This only occurs when working with qdrant client and qdrant server (running in docker container), and not when using qdrant client alone.

```python
from qdrant_client import QdrantClient, models

client = QdrantClient(host="localhost", port=6334, prefer_grpc=True)

# Create collection
client.create_collection(
    collection_name="test_collection",
    vectors_config=models.VectorParams(
        size=4,
        distance=models.Distance.COSINE,
        multivector_config=models.MultiVectorConfig(
            comparator=models.MultiVectorComparator.MAX_SIM
        ),
    ),
)

# Do a search using a random multivector
search_results = client.search(
    collection_name="test_collection",
    query_vector=[[-0.013,  0.020, -0.007, -0.111], [-0.030, -0.055,  0.001,  0.072], [-0.041,  0.014, -0.032, -0.062]],
    limit=3
)
```

## Steps to Reproduce
1. I am using qdrant-client version 1.10.1 and qdrant container version 1.10.1. Here is the docker-compose file I am using to run qdrant server:
```
services:
  qdrant:
    image: qdrant/qdrant:v1.10.1
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
configs:
  qdrant_config:
    content: |
      log_level: INFO
```
2. Copy and paste the above python code into a file once qdrant-client is installed and qdrant server is running. Run the python code and you will see this error:
```
TypeError: [-0.013, 0.02, -0.007, -0.111] has type list, but expected one of: int, float
```
There will be an error regardless of whether prefer_grpc is True or False when declaring QdrantClient

## Expected Behavior
When qdrant server is not used, for example when qdrant client is declared like this:
```python
client = QdrantClient(":memory")
# OR
client = QdrantClient(path="test_path")
```
In this case, the error does not occur, and querying with a multivector works properly. This is the expected behaviour.

I would like to note that upserting a multivector into a collection works correctly, it is only the searching that causes an issue. 

## Possible Solution
I'm assuming the searching code/function in qdrant-client and in qdrant must have some difference, and maybe that's why this issue only occurs when using qdrant server; ormaybe there's some difference in usage that I haven't accounted for.

## Context (Environment)
I'm trying to work with multivectors, which according to [here](https://qdrant.tech/documentation/concepts/vectors/#multivectors) should be supported.
