### ISSUE TITLE
Snapshot shows unknown when using NFS in snapshot folder

### ISSUE THREAD

**Issue by BlueBlueSummer** [qdrant/qdrant#4862]
Snapshot shows unknown when using NFS in snapshot folder

## Current Behavior

Create at filed shows **unknown** instead of specific timestamp
<img width="1521" alt="image" src="https://github.com/user-attachments/assets/6675ebc5-eb98-495f-bd84-bb9c8b810f03">

## Steps to Reproduce

1. Set an EFS to snapshot volum,
```
config:
  storage:
    snapshots_path: ./efs-snapshots

additionalVolumes:
  - name: efs-mount
    nfs:
      path: /
      server: fs-xxxxx.efs.eu-central-1.amazonaws.com

additionalVolumeMounts:
  - name: efs-mount
    mountPath: "/qdrant/efs-snapshots"
```
2. Create a snapshot for a collection
3. Then **Create at** filed shows **unknown** instead of specific timestamp

## Expected Behavior

Create at filed should show a specific timestamp
