### ISSUE TITLE
Feature Request: configuration option to disable WebUI for production

### ISSUE THREAD

**Issue by freinold** [qdrant/qdrant#5153]
**Is your feature request related to a problem? Please describe.**
When running Qdrant on our own K8s Cluster in Production, we want to ensure the deployment is optimized for security and performance. For this reason, we would like to disable the WebUI component completely because our production setup has no need for it.

**Describe the solution you'd like**
Ideally, there should be another key inside the the `config.yaml` like this:

```yaml
# WebUI configuration (see /dashboard on your HTTP port)
webui:
  # enabled by default, disable this for production environments
  enabled: true
```
