### ISSUE TITLE
Failed to start Qdrant pods: OS can't spawn worker thread: Resource temporarily unavailable (os error 11)

### ISSUE THREAD

**Issue by markkofler** [qdrant/qdrant#5544]
We noticed today our 3-node qdrant cluster is no longer starting. When looking into the logs, it shows somehow a problem at the end of the loading of all collections with spawning pods:

```
024-11-28T14:29:22.661645Z ERROR qdrant::startup: Panic occurred in file /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/connect/dns.rs at line 121: OS can't spawn worker thread: Resource temporarily unavailable (os error 11)
thread panicked while processing panic. aborting.
```

## Current Behavior
The qdrant pods inside of a Kubernetes cluster keep crashing after the collection loading phase. Qdrant is not able to start currently.

## Background Information
- We are running our qdrant cluster inside of a Kubernetes cluster (v1.28)
- We are using qdrant version 1.6.1
- Our Qdrant Cluster includes multiple 1000 collections with user data
- The problem started to occur after we increased the memory of our qdrant pods to 20GB memory. This was necessary, as the pod was previously running out of memory multiple times.

## Current Qdrant Config
```yaml
log_level: DEBUG

cluster:
  consensus:
    tick_period_ms: 100
  enabled: true
  p2p:
    port: 6335
```

## Tested Solutions
- After some online research, we found this problem might be related to a reached max number of threads. For this reason, we tried to limiting the number of threads spawned by qdrant using the following configuration:

```yaml
log_level: DEBUG

storage:
  performance:
    max_search_threads: 5
    max_optimization_threads: 8
  hnsw_index:
    max_indexing_threads: 8

service:
  max_workers: 5

cluster:
  consensus:
    tick_period_ms: 100
  enabled: true
  p2p:
    port: 6335

telemetry_disabled: true
```

After starting the qdrant pods with this config, the pods crash with a different message:

```
[2m2024-11-28T18:59:18.336020Z[0m [32m INFO[0m [2mstorage::content_manager::toc[0m[2m:[0m Loading collection: PRD-ecf5b6e4-23a0-487e-8701-9d83adf44519.8a260d0d409ee9e3ad2c838801f4984770ae44c588306ade33e202dd2adda2e9    
[2m2024-11-28T18:59:18.507050Z[0m [32m INFO[0m [2mstorage::content_manager::toc[0m[2m:[0m Loading collection: PRD-83babb4e-3e0e-4859-9429-5aa39ab9aea7.a33668e91cc0e51776f1a0cc8be1204ecd8a62134c8a93936fd6eade05921579    
[2m2024-11-28T18:59:18.681941Z[0m [32m INFO[0m [2mstorage::content_manager::toc[0m[2m:[0m Loading collection: PRD-567228e0-9862-4892-95ac-5911f77ef312.379c9b29b3c6b7b82e5a1791e5fa28717338bbb8c237666f599af69d8af2b061    
[2m2024-11-28T18:59:18.851344Z[0m [32m INFO[0m [2mstorage::content_manager::toc[0m[2m:[0m Loading collection: PRD-58f89640-f5f6-467e-a610-9446d2420ec3.45b62391e776963b47f7d739391f47d34ffef8bf0f6badbe897f2c2566865377    
[2m2024-11-28T18:59:19.026584Z[0m [32m INFO[0m [2mstorage::content_manager::toc[0m[2m:[0m Loading collection: PRD-65d212cf-90fc-483d-bbcc-421f13225cea.e993c6d152b00f69be845abfcc05de4e35729cb49193af17921991c75bce1688    
terminate called without an active exception
./entrypoint.sh: line 25:     7 Aborted                 (core dumped) ./qdrant $@

```

Also, we thought the error might be occurring at some point because of a Kubernetes readiness probe. For this reason, we completely disabled the probe, which did not fix the problem.

Summarized, we do not know how to proceed or where the error is coming from at this point in time. Has anybody seen this issue before and can help us further?

**Comment by superseb** [comment]
Can you share a bit more details on the cluster/nodes? Did the pods get scheduled to a different node, with maybe different configuration? What is the configuration of the cluster/node/pod? At first it seems like an issue with resources, which of course could be initiated due to some bug in the code but I want to know a bit more about the setup too.

Is it always after `PRD-65d212cf-90fc-483d-bbcc-421f13225cea.e993c6d152b00f69be845abfcc05de4e35729cb49193af17921991c75bce1688`? Is that also the last one or are there more?

**Comment by markkofler** [comment]
Of course so here are more details based on your questions:

**Did the pods get scheduled to a different node, with maybe different configuration?**

Answer: All of the 3 replicas / pods are scheduled on different pods, but as all pods are instances of the same StatefulSet, the configuration is the same

**What is the configuration of the cluster/node/pod?**

Answer: Here are the configmap and statefulset YAMLs of the current setup.

StatefulSet:
```yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  annotations:
    meta.helm.sh/release-name: qdrant
    meta.helm.sh/release-namespace: example
  name: qdrant
  namespace: gpt4ifx
  labels:
    app: qdrant
    app.kubernetes.io/instance: qdrant
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/version: v1.11.0
    helm.sh/chart: qdrant-1.11.0
spec:
  serviceName: qdrant-headless
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: qdrant-storage
        creationTimestamp: null
        labels:
          app: qdrant
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        volumeMode: Filesystem
      status:
        phase: Pending
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: qdrant-snapshots
        creationTimestamp: null
        labels:
          app: qdrant
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qdrant
        app.kubernetes.io/instance: qdrant
        app.kubernetes.io/name: qdrant
      annotations:
        checksum/config: ede531f3d485670a35fb2423ec536b144a243b913062ef91d1af135fc03ac31c
    spec:
      restartPolicy: Always
      serviceAccountName: qdrant
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '5'
              memory: 20Gi
            requests:
              cpu: '5'
              memory: 20Gi
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6333
              scheme: HTTP
            initialDelaySeconds: 240
            timeoutSeconds: 300
            periodSeconds: 100
            successThreshold: 1
            failureThreshold: 80
          terminationMessagePath: /dev/termination-log
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '3'
          name: qdrant
          command:
            - /bin/bash
            - '-c'
          env:
            - name: QDRANT_INIT_FILE_PATH
              value: /qdrant/init/.qdrant-initialized
            - name: QDRANT_ALLOW_RECOVERY_MODE
              value: 'true'
          ports:
            - name: http
              containerPort: 6333
              protocol: TCP
            - name: grpc
              containerPort: 6334
              protocol: TCP
            - name: p2p
              containerPort: 6335
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
            - name: qdrant-config
              mountPath: /qdrant/config/initialize.sh
              subPath: initialize.sh
            - name: qdrant-config
              mountPath: /qdrant/config/production.yaml
              subPath: production.yaml
            - name: qdrant-snapshots
              mountPath: /qdrant/snapshots
            - name: qdrant-init
              mountPath: /qdrant/init
          terminationMessagePolicy: File
          image: 'dockerregistry-v2.example.com/qdrant/qdrant:v1.11.0'
          args:
            - ./config/initialize.sh
      serviceAccount: qdrant
      volumes:
        - name: qdrant-config
          configMap:
            name: qdrant
            defaultMode: 493
        - name: qdrant-init
          emptyDir: {}
      dnsPolicy: ClusterFirst
  podManagementPolicy: Parallel
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app: qdrant
      app.kubernetes.io/instance: qdrant
      app.kubernetes.io/name: qdrant
status:
  observedGeneration: 21
  replicas: 3
  updatedReplicas: 3
  currentRevision: qdrant-99f967b4d
  updateRevision: qdrant-64d9d55656
  collisionCount: 0
  availableReplicas: 0
```

ConfigMap:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: qdrant
  namespace: example
  labels:
    app: qdrant
    app.kubernetes.io/instance: qdrant
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/version: v1.11.0
    helm.sh/chart: qdrant-1.11.0
  annotations:
    meta.helm.sh/release-name: qdrant
    meta.helm.sh/release-namespace: example
data:
  initialize.sh: |
    #!/bin/sh
    SET_INDEX=${HOSTNAME##*-}
    echo "Starting initializing for pod $SET_INDEX"
    if [ "$SET_INDEX" = "0" ]; then
      exec ./entrypoint.sh --uri 'http://qdrant-0.qdrant-headless:6335'
    else
      exec ./entrypoint.sh --bootstrap 'http://qdrant-0.qdrant-headless:6335' --uri 'http://qdrant-'"$SET_INDEX"'.qdrant-headless:6335'
    fi
  production.yaml: |
    storage:
      performance:
        max_search_threads: 5
        max_optimization_threads: 8
      hnsw_index:
        max_indexing_threads: 8

    service:
      max_workers: 5

    cluster:
      enabled: true
      p2p:
        port: 6335
      consensus:
        tick_period_ms: 100
    telemetry_disabled: true
```

**Is it always after PRD-65d212cf-90fc-483d-bbcc-421f13225cea.e993c6d152b00f69be845abfcc05de4e35729cb49193af17921991c75bce1688? Is that also the last one or are there more?**

Answer: I was seeing this collection name re-appearing after panic messages of multiple of the replicas. Therefore, I have booted the qdrant pods now using a forced OOM into recovery mode and deleted the collection. However, new collection continue to appear and after deleting some, it seems more and more collections are appearing before panic events or errors so not sure if this is now really related to the specific collections. Here is 1 example for each of the two error messages which keep appearing after collection names, right before the instances crash:

Example one (panic event):
```
2024-11-29T21:12:10.302035Z  INFO storage::content_manager::toc: Loading collection: PRD-c70e2d14-e4b3-49ce-8b81-d285431c0acf.a3a9f76fc2adea262475324d2b4fd94486faa3f4b36b0e3fe8d65bf47b199776    
2024-11-29T21:12:10.405697Z ERROR qdrant::startup: Panic backtrace: 
   0: qdrant::startup::setup_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: wal::segment::Segment::flush_async
   8: collection::update_handler::UpdateHandler::flush_worker::{{closure}}
   9: tokio::runtime::task::raw::poll
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  11: tokio::runtime::scheduler::multi_thread::worker::run
  12: tokio::runtime::task::raw::poll
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::pal::unix::thread::Thread::new::thread_start
  16: <unknown>
  17: <unknown>
    
2024-11-29T21:12:10.405745Z ERROR qdrant::startup: Panic occurred in file /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/thread/mod.rs at line 698: failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }    
terminate called without an active exception
terminate called recursively
./entrypoint.sh: line 25:     7 Aborted                 (core dumped) ./qdrant $@
```

Example 2 (termination message):
```
2024-11-29T20:38:00.410061Z  INFO storage::content_manager::toc: Loading collection: PRD-58232c7a-2e43-4d0a-9c06-973ce2a0d4d1.d65ddde386d7d8a023deeb16ab661be94a5da9624c0ec063167ffe38174c8823    
terminate called without an active exception
```

Hope those were the details you were looking for. Thanks in advance for the help!
