### ISSUE TITLE
Error on enabling quantization: invalid type: integer `1536`, expected struct VectorParamsDiff

### ISSUE THREAD

**Issue by itinance** [qdrant/qdrant#5874]
I want to enable Binary Quantization on an collection, following the official Docs:  https://qdrant.tech/documentation/guides/quantization/?q=quantization

## Current Behavior

Sending the CURL request to a qdrant instance according to the docs, responds with an error, complaining about the integer for vector size:

```
curl  -X PATCH \
  'http://localhost:6336/collections/embeddings_ada' \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "vectors": {
      "size": 1536,
      "distance": "Cosine"
    },
    "quantization_config": {
        "binary": {
            "always_ram": true
        }
    }
}'
```

Result/Error:

`{"status":{"error":"Format error in JSON body: invalid type: integer `1536`, expected struct VectorParamsDiff at line 3 column 18"},"time":0.0}%  `

## Steps to Reproduce

1. Setting up Qdrant, e.g. via Docker:

```
version: '3.8'

services:
  qdrant_embed:
    image: qdrant/qdrant:v1.12.5
    container_name: qdrant_core
    ports:
      - "6336:6333"
    volumes:
      - ../qdrant-core-storage:/qdrant/storage
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```

2. Setting up a collection, without quantization at this point
3. Updating collection for binary quantization:

```
curl  -X PATCH \
  'http://localhost:6336/collections/embeddings_ada' \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "vectors": {
      "size": 1536,
      "distance": "Cosine"
    },
    "quantization_config": {
        "binary": {
            "always_ram": true
        }
    }
}'


```
## Expected Behavior

It would accept the payload as provided in the Docs.

## Possible Solution

Removing the vectors-part and submitting only the `quantization_config` in the payload works:

```
curl  -X PATCH \
  'http://localhost:6336/collections/embeddings_ada' \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "quantization_config": {
        "binary": {
            "always_ram": true
        }
    }
}'
```

## Context (Environment)

1. Qdrant v1.12.5 via Docker
2. running docker on MacOS via orbStack

## Detailed Description

I want to enable Binary Quantization on an existing collection, following the official Docs:  https://qdrant.tech/documentation/guides/quantization/?q=quantization

However, sending the CURL request to a qdrant instance according to the docs, responds with an error, complaining about the integer for vector size.

## Possible Implementation

Removing the vectors-part and submitting only the `quantization_config` in the payload works:

```
curl  -X PATCH \
  'http://localhost:6336/collections/embeddings_ada' \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "quantization_config": {
        "binary": {
            "always_ram": true
        }
    }
}'
```
