### ISSUE TITLE
Qdrant在Linux的安装（Qdrant installation on Linux (without relying on docker)）

### ISSUE THREAD

**Issue by beyondhj** [qdrant/qdrant#6168]
# Qdrant安装指北

截至版本1.13.4

## 0. 环境检查

Qdrant依赖环境信息如下：

- GLIBC 2.39
- GLIBCXX 3.4.30(对应 gcc-12.4.0)
- CXXABI 1.3.13

如上述条件均满足，可直接跳过，从 ***1. Qdrant安装*** 开始

### 0.1. GLIBC安装

[官网下载地址](https://ftp.gnu.org/gnu/glibc/)

下载并解压`glibc-2.39.tar.gz`后，以`/opt/glibc/glibc-2.39-src`为例

#### 0.1.1. GLIBC依赖检查

```bash
# 在解压文件夹glibc-2.39下
cat INSTALL | grep -E 'newer|later'
```

检查相关依赖是否满足，包含：

- `make` 4.0+
- `gdb` 7.8+
- `python` 3.4+
- `binutils` 2.26+
- `texinfo` 4.7+
- `bison` 2.7+
- `sed` 3.02+
- `gettext` 0.10.36+

#### 0.1.2. GLIBC编译与配置

在其他目录下创建一个新目录，以`/opt/glibc/glibc-2.39-build`为例

```bash
/opt/glibc/glibc-2.34-src/configure --prefix=/opt/ld-cpl --disable-profile --enable-add-ons --with-headers=/usr/include --with-binutils=/usr/bin --disable-sanity-checks --disable-werror
```

执行完成且没有error出现后执行

```bash
# 4 为可调整参数，用于设置编译使用线程数
make -j4
```

执行完成且报错后执行

```bash
make install
```

此时，编译完成的lib库将会保存在`/opt/ld-cpl`中，使用`patchelf`将新的`glibc`动态寻址路径写入`qdrant`可执行文件中

```bash
patchelf --set-interpreter /opt/ld-cpl/lib/ld-linux-x86-64.so.2 /path/to/qdrant
```

### 0.2. GLIBCXX及CXXABI安装

[官网下载地址](https://ftp.gnu.org/gnu/gcc/)

下载并解压`glibc-2.39.tar.gz`后，以`/opt/glibc/glibc-2.39-src`为例

#### 0.2.1. 检查GCC相关依赖

GCC编译依赖于以下内容：

- `GMP` 4.3.2+
- `MPFR` 3.1.0+
- `MPC` 1.0.1+

#### 0.2.2. GCC编译与配置

在其他目录下创建一个新目录，以`/opt/glibc/gcc-12.4.0-build`为例

```bash
/opt/glibc/gcc-12.4.0-src/configure --prefix=/opt/ld-cpl --disable-multilib
```

执行完成且没有error出现后执行

```bash
# 4 为可调整参数，用于设置编译使用线程数
make -j4
```

执行完成且报错后执行

```bash
make install
```

此时，编译完成的lib库将会保存在`/opt/ld-cpl`中，使用`patchelf`将新的`gcc`动态寻址路径写入`qdrant`可执行文件中

```bash
patchelf --set-rpath /opt/ld-cpl/lib64 /path/to/qdrant
```

## 1. Qdrant安装

下载并解压`qdrant-x86_64-unknown-linux-gnu.tar.gz`，解压文件为qdrant二进制文件

```bash
# 给予可执行权限
chmod +x qdrant
```

### 1.1. 创建配置文件

```yaml
log_level: INFO
storage:
  storage_path: ./storage
  snapshots_path: ./snapshots
  snapshots_config:
    # "local" or "s3" - where to store snapshots
    snapshots_storage: local
    # s3_config:
    #   bucket: ""
    #   region: ""
    #   access_key: ""
    #   secret_key: ""
service:
  max_request_size_mb: 32
  max_workers: 0
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  enable_cors: true
  enable_tls: false
  verify_https_client_certificate: false

cluster:
  enabled: false
  p2p:
    port: 6335
    enable_tls: false
  consensus:
    tick_period_ms: 100
    compact_wal_entries: 128
telemetry_disabled: false
```

## 1.2. 运行Qdrant

```bash
nohup /path/to/qdrant --config-path=/path/to/config.yaml > /path/to/qdrant.log 2>&1 &
