### ISSUE TITLE
Qdrant in Azure Container Instances: TLS

### ISSUE THREAD

**Issue by MarinaJim** [qdrant/qdrant#6204]
When using qdrant (qdrant/qdrant:v1.13.4 from dockerhub) with Azure Container Instances, Qdrant does not find TLS private key. Therefore, connection via HTTPS can not be enabled

I create my container from a yaml file, where I set the environmental variables and volume mounting for TLS as follows:
...
environmentalVariables:
        - name: QDRANT__TLS__CERT
          value: /qdrant/tls/cert.pem
        - name: QDRANT__TLS__KEY
          value: /qdrant/tls/key.pem
        - name: QDRANT__SERVICE__ENABLE_TLS
          value: true 
...
volumeMounts:
      - mountPath: /qdrant/tls
        name: qdranttls
...

I get the following error:
          _                 _    
  __ _  __| |_ __ __ _ _ __ | |_  
 / _` |/ _` | '__/ _` | '_ \| __| 
| (_| | (_| | | | (_| | | | | |_  
 \__, |\__,_|_|  \__,_|_| |_|\__| 
    |_|                           

Version: 1.13.4, build: 7abc6843
Access web UI at https://localhost:6333/dashboard

2025-03-18T16:34:16.971542Z  WARN qdrant: Bootstrap URI is the same as this peer URI. Consider this peer as a first in a new deployment.    
2025-03-18T16:34:16.999777Z  INFO storage::content_manager::consensus::persistent: Loading raft state from ./storage/raft_state.json    
2025-03-18T16:34:17.321877Z  INFO qdrant: Distributed mode disabled    
2025-03-18T16:34:17.322215Z  INFO qdrant: Telemetry reporting enabled, id: 9ccad83b-a1db-431d-af55-e1fecee9a5df    
2025-03-18T16:34:17.323548Z  INFO qdrant: Inference service is not configured.    
2025-03-18T16:34:17.329383Z  INFO qdrant::actix: TLS enabled for REST API (TTL: 3600)    
2025-03-18T16:34:17.332055Z  INFO qdrant::tonic: Qdrant gRPC listening on 6334    
2025-03-18T16:34:17.332102Z  INFO qdrant::tonic: TLS enabled for gRPC API (TTL not supported)    
2025-03-18T16:34:17.618199Z ERROR qdrant: Error while starting REST server: no private key found    
Error: no private key found

However, when I connect to the container and do ``ls qdrant/tls``, I can see key.pem file, so the path is correct

**Comment by generall** [comment]
Hey! We do not provide support for Azure Container Instances. Please formulate your problem in either pure qdrant docker/binary configuratuin, or prefer Qdrant Cloud instead

**Comment by MarinaJim** [comment]
Hi,

I have now reproduced the same error locally: 

1. `openssl req -x509 -newkey rsa:4096 -days 365 -keyout key.pem -out cert.pem`
2. Create `config.yaml`:
service:
  enable_tls: true
tls:
  cert: ./tls/cert.pem
  key: ./tls/key.pem

```
3. docker run -p 6333:6333 -v $(pwd)/config/config.yaml:/qdrant/config/config.yaml -v $(pwd)/tls:/qdrant/tls qdrant/qdrant:v1.13.4
Output:
2025-03-20T09:20:44.357973Z  INFO qdrant::actix: TLS enabled for REST API (TTL: 3600)    
2025-03-20T09:20:44.361703Z  INFO qdrant::tonic: Qdrant gRPC listening on 6334
2025-03-20T09:20:44.361754Z  INFO qdrant::tonic: TLS enabled for gRPC API (TTL not supported)
2025-03-20T09:20:44.374969Z ERROR qdrant: Error while starting REST server: no private key found    
Error: no private key found

**Comment by Ch41r05** [comment]
Are there updates about this matter?
I'm experiencing the same kind of behaviour on dockerized qdrant, and I'm also using a similar scaffolding to the one @MarinaJim reported.

What I can add are the configs for docker compose and my config:

docker compose

```
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    # enable_tls: true
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    ports:
      - "6333:6333"
      - "6334:6334"
    command: ./qdrant --config-path /qdrant/config/tls_config.yaml
    volumes:
      - ./tls:/qdrant/tls
      - ./config/qdrant/tls_config.yaml:/qdrant/config/tls_config.yaml:ro
      - qdrant_data:/qdrant/storage:z

volumes:
  qdrant_data:
```

config

```
log_level: INFO

service:
  # Use TLS for client communication
  enable_tls: true

  # Check user HTTPS client certificate against CA file specified in tls config
  verify_https_client_certificate: true

# TLS settings
tls:
  # Certificate chain file
  cert: ./tls/cert.pem

  # Private key file
  key: ./tls/key.pem

  # Client certificate
  ca_cert: ./tls/ca_cert.pem
```
