### ISSUE TITLE
Error: in docker cluster mode with TLS enabled - No such file or directory (os error 2)

### ISSUE THREAD

**Issue by sinawic** [qdrant/qdrant#6273]
when TLS enabled, peers can't connect to each other as i'm guessing based on somehow related issues.
my certs are self signed with command `mkcert qdrant.com qdrant1.com qdrant2.com qdrant3.com 1.2.3.4`

uname -a:
`Linux sinawic 6.8.0-52-generic #53~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 15 19:18:46 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

## Current Behavior

i get different errors when i enable/disable some environment variables

i get
```
2025-03-29T07:20:19.937147Z  INFO storage::content_manager::consensus::persistent: Loading raft state from /qdrant/storage/raft_state.json    
Error: No such file or directory (os error 2)
```
when `QDRANT__CLUSTER__P2P__ENABLE_TLS=true`

i unset QDRANT__CLUSTER__P2P__ENABLE_TLS

then the first instance comes up with:
`./entrypoint.sh --uri https://1.2.3.4:63351`

then the second instance with:
`./entrypoint.sh --uri https://1.2.3.4:63352 --bootstrap https://1.2.3.4:63351`

but the error i get is:
```
Version: 1.13.5, build: e282ed91
Access web UI at https://localhost:6333/dashboard

2025-03-29T07:30:56.279332Z  INFO storage::content_manager::consensus::persistent: Initializing new raft state at /qdrant/storage/raft_state.json    
Error: No such file or directory (os error 2)
```

here is my docker-compose file:
```yaml
version: '3'
services:
  qdrant1:
    image: qdrant/qdrant:v1.13.5
    restart: always
    container_name: qdrant1
    ports:
      - 63331:6333
      - 63341:6334
      - 63351:6335
    volumes:
      - ./data1:/qdrant/storage
      - ./snapshots1:/qdrant/snapshots
      - ./certs:/certs:ro
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__STORAGE__SNAPSHOTS_PATH=/qdrant/snapshots
      - QDRANT__SERVICE__API_KEY=sdlVp9fPBtjxxxN5hMYLBjaq5sw6QMhF
      - QDRANT__SERVICE__ENABLE_TLS=1
      - QDRANT__TLS__CERT=/certs/qdrant.com.pem
      - QDRANT__TLS__KEY=/certs/qdrant.com-key.pem
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__SERVICE__VERIFY_HTTPS_CLIENT_CERTIFICATE=false
      - QDRANT__CLUSTER__P2P__ENABLE_TLS=true
    command: ["./entrypoint.sh", "--uri", "https://1.2.3.4:63351"]

  qdrant2:
    image: qdrant/qdrant:v1.13.5
    restart: always
    container_name: qdrant2
    ports:
      - 63332:6333
      - 63342:6334
      - 63352:6335
    volumes:
      - ./data2:/qdrant/storage
      - ./snapshots2:/qdrant/snapshots
      - ./certs:/certs:ro
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__STORAGE__SNAPSHOTS_PATH=/qdrant/snapshots
      - QDRANT__SERVICE__API_KEY=sdlVp9fPBtjxxxN5hMYLBjaq5sw6QMhF
      - QDRANT__SERVICE__ENABLE_TLS=1
      - QDRANT__TLS__CERT=/certs/qdrant.com.pem
      - QDRANT__TLS__KEY=/certs/qdrant.com-key.pem
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__SERVICE__VERIFY_HTTPS_CLIENT_CERTIFICATE=false
      - QDRANT__CLUSTER__P2P__ENABLE_TLS=true
    command: ["./entrypoint.sh", "--uri", "https://1.2.3.4:63352", "--bootstrap", "https://1.2.3.4:63351"]

  qdrant3:
    image: qdrant/qdrant:v1.13.5
    restart: always
    container_name: qdrant3
    ports:
      - 63333:6333
      - 63343:6334
      - 63353:6335
    volumes:
      - ./data3:/qdrant/storage
      - ./snapshots3:/qdrant/snapshots
      - ./certs:/certs:ro
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__STORAGE__SNAPSHOTS_PATH=/qdrant/snapshots
      - QDRANT__SERVICE__API_KEY=sdlVp9fPBtjxxxN5hMYLBjaq5sw6QMhF
      - QDRANT__SERVICE__ENABLE_TLS=1
      - QDRANT__TLS__CERT=/certs/qdrant.com.pem
      - QDRANT__TLS__KEY=/certs/qdrant.com-key.pem
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__ENABLE_TLS=true
      - QDRANT__SERVICE__VERIFY_HTTPS_CLIENT_CERTIFICATE=false
    command: ["./entrypoint.sh", "--uri", "https://1.2.3.4:63353", "--bootstrap", "https://1.2.3.4:63351"]
```

## Expected Behavior

at least throw some detailed error on where the exact thing is that is causing the error
or to come up and connect successfully to the first instance
