### ISSUE TITLE
Too many open files with Docker

### ISSUE THREAD

**Issue by gaby** [qdrant/qdrant#6358]
I'm having the same problem as all the other `too many files open` tickets. In my case qdrant is being used as the VectorDB for Open-WebUI. Uploading more than 100-150 files in a chat throws a `Too many files open` error and everything basically doesn't work going forward.

- qdrant is running in docker
- linux system
- limits.conf are set to 65,535 for all of them.
- docker daemon also has the setting set
- docker compose also has the setting set
- embedding is set to `1000` chunks. Changing this made no difference.

Spent an hour trying to figure out how to use the `config.yaml` to force the `quantization` to be always ram. I have the following (not sure if it even works since it still uses disk):

```yaml
log_level: info

quantization:
  always_ram: True

storage:
  on_disk_payload: False

  collections:
    vectors:
      on_disk: False  
```

Each collection still gets written to disk on a brand new instance of `qdrant`. My guess is the `quantization` field is being ignored? I tried adding it under `storage.collection.quantization` but it throws `enum` exceptions. For any field I try to use. For ex:

```yaml
storage:
  collections:
    quantization:
      type: int8
```

The system has over 500GB of RAM, ideally we want to do as much as possible in RAM and only write to disk for storing if not used. I'm not sure the implications of all the `disk` config options.

Open-WebUI creates a collection for every Chat files for embedding.
