### ISSUE TITLE
GCS bucket snapshots storage feature: Not able to store snapshots in GCS bucket

### ISSUE THREAD

**Issue by prathmesh-chopade** [qdrant/qdrant#6482]
Unable to create a snapshot when using a GCS bucket for storage with Qdrant. The snapshot creation API call fails with a **500 Internal Server Error**, and the logs indicate an S3-related issue: **411 Length Required**. This might be due to incompatibility between GCS and how multipart uploads are handled in the current S3-compatible setup.

## Current Behavior

Cannot create a snapshot after setting up GCS bucket configuration. The server returns a 500 error during the snapshot creation process.

## Steps to Reproduce

1. Create a GCS bucket and obtain credentials with admin rights.
2. Add the following environment variables in your Helm chart values.yaml (as documented [here](https://qdrant.tech/documentation/concepts/snapshots/#s3))

```
env:
  - name: QDRANT__STORAGE__SNAPSHOTS_CONFIG__SNAPSHOTS_STORAGE
    value: "s3"
  - name: QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__BUCKET
    value: "<GCS bucket name>"
  - name: QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__ENDPOINT_URL
    value: "http://storage.googleapis.com"
  - name: QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__ACCESS_KEY
    value: "<GCS bucket access key>"
  - name: QDRANT__STORAGE__SNAPSHOTS_CONFIG__S3_CONFIG__SECRET_KEY
    value: "<GCS bucket secret key>"
```

3. Deploy the Helm chart and try to create a snapshot using the snapshot API.
Error: Http Status - 500 internal server error
API Response:
```
{
    "status": {
        "error": "Service internal error: failed to store snapshot archive to /qdrant/./storage/tmp/test-collection-1867518375793437-2025-05-02-11-24-39.snapshot-arc-fgnzy7: Service internal error: Failed to put multipart: Generic S3 error: Client error with status 411 Length Required: <!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 411 (Length Required)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>411.</b> <ins>That’s an error.</ins>\n  <p>POST requests require a <code>Content-length</code> header.  <ins>That’s all we know.</ins>\n"
    },
    "time": 1.332312
}
```

## Expected Behavior

The snapshot should be created and uploaded to the GCS bucket successfully without errors.

## Possible Solution

It seems GCS may not fully support the same multipart upload behavior expected from AWS S3 (specifically, missing Content-Length headers). Qdrant might need to either:

Use a different upload strategy for GCS, or boto3
Allow configuration overrides specific to GCS quirks.

Refer to a similar issue closed earlier: https://github.com/qdrant/qdrant/issues/4701

## Context (Environment)

Qdrant Version: v1.13.6
Deployment method: Helm on GKE (private setup)
Storage backend: GCS with S3-compatible interface
OS: Linux container
Kubernetes: v1.31

## Detailed Description

I am trying to leverage Qdrant's snapshot feature using a GCS bucket for storage. Despite GCS advertising S3-compatibility, Qdrant appears to expect headers or behaviors specific to AWS S3, which causes the snapshot API to fail.

This issue affects automated backups and disaster recovery workflows using Qdrant.

## Possible Implementation

An enhancement to support native GCS APIs or adjust multipart upload expectations (e.g., always setting Content-Length headers) when using GCS as the S3 endpoint could resolve this.
Alternatively, providing a dedicated config option like **gcs_compat_mode = true** might help apply workarounds specific to GCS behavior.
