### ISSUE TITLE
Setting cluster::p2p::enable_tls to true causes Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by larrydewey** [qdrant/qdrant#6767]
I am attempting to enable TLS protection between clusters and for http/grpc. However, whenever I turn this on, I am getting:

```
Jun 26 14:38:38 dev1 qdrant[43300]:            _                 _
Jun 26 14:38:38 dev1 qdrant[43300]:   __ _  __| |_ __ __ _ _ __ | |_
Jun 26 14:38:38 dev1 qdrant[43300]:  / _` |/ _` | '__/ _` | '_ \| __|
Jun 26 14:38:38 dev1 qdrant[43300]: | (_| | (_| | | | (_| | | | | |_
Jun 26 14:38:38 dev1 qdrant[43300]:  \__, |\__,_|_|  \__,_|_| |_|\__|
Jun 26 14:38:38 dev1 qdrant[43300]:     |_|
Jun 26 14:38:38 dev1 qdrant[43300]: Version: 1.14.1, build: 530430fa
Jun 26 14:38:38 dev1 qdrant[43300]: Access web UI at http://localhost:1025/dashboard
Jun 26 14:38:38 dev1 qdrant[43300]: 2025-06-26T20:38:38.983792Z  WARN qdrant::settings: Config file not found: config/config
Jun 26 14:38:38 dev1 qdrant[43300]: 2025-06-26T20:38:38.983805Z  WARN qdrant::settings: Config file not found: config/development
Jun 26 14:38:38 dev1 qdrant[43300]: 2025-06-26T20:38:38.983816Z  WARN qdrant: Bootstrap URI is the same as this peer URI. Consider this peer as a first in a new deployment.
Jun 26 14:38:38 dev1 qdrant[43300]: 2025-06-26T20:38:38.983827Z  INFO storage::content_manager::consensus::persistent: Loading raft state from /var/lib/qdrant/vdb-storage/raft_state.json
Jun 26 14:38:38 dev1 qdrant[43300]: Error: No such file or directory (os error 2)
```

## Current Behavior
Qdrant fails to start returning an ill-defined error:

```
Jun 26 14:38:38 dev1 qdrant[43300]: Error: No such file or directory (os error 2)
```

## Steps to Reproduce

1. Download the qdrant v1.14.1 binary from github.
2. Extract the binary onto Fedora 42 system.
3. Store the binary at `/usr/bin/qdrant`
4. Store the following custom config at `/etc/qdrant/config.yaml`:
    ```yaml
    log_level: "INFO"

    storage:
        storage_path: "/var/lib/qdrant/qdrant-storage"
        snapshots_path: "/var/lib/qdrant/qdrant-snapshots"
        snapshots_config:
            snapshots_storage: local
        temp_path: null
        on_disk_payload: true
        update_concurrency: null
        wal:
            wal_capacity_mb: 32
            wal_segments_ahead: 0
        node_type: "Normal"
        performance:
            max_search_threads: 0
            max_optimization_threads: 0
            optimizer_cpu_budget: 0
            update_rate_limit: null
        optimizers:
            deleted_threshold: 0.2
            vacuum_min_vector_number: 1000
            default_segment_number: 0
            max_segment_size_kb: null
            memmap_threshold_kb: null
            indexing_threshold_kb: 20000
            flush_interval_sec: 5
            max_optimization_threads: null
        hnsw_index:
            m: 16
            ef_construct: 100
            full_scan_threshold_kb: 10000
            max_indexing_threads: 0
            on_disk: false
            payload_m: null
        shard_transfer_method: null
        collection:
            replication_factor: 1
            write_consistency_factor: 1
            vectors:
                on_disk: null
            quantization: null
            strict_mode:
                enabled: false
                max_query_limit: null
                max_timeout: null
                unindexed_filtering_retrieve: null
                unindexed_filtering_update: null
                search_max_hnsw_ef: null
                search_allow_exact: null
                search_max_oversampling: null
        max_collections: null
    
    service:
        max_request_size_mb: 32
        max_workers: 0
        host: 0.0.0.0
        http_port: 4321
        grpc_port: 4322
    
    
    cluster:
        enabled: true
        p2p:
            port: 4323
            enable_tls: true
        consensus:
            tick_period_ms: 100
            compact_wal_entries: 128
    
    telemetry_disabled: false
    
    tls:
        cert_file: "/etc/pki/tls/qdrant/qdrant.crt"
        key_file: "/etc/pki/tls/qdrant/qdrant-key.pem"
        cert_ttl: 3600

    ```
5. Start the binary on each machine:
    - Primary Node:
      ```bash
      Execute `/usr/bin/qdrant --config-path /etc/qdrant/config.yaml --uri <fqdn>:<port>
      ```
    - Other Nodes:
      ```bash
      Execute `/usr/bin/qdrant --config-path /etc/qdrant/config.yaml --bootstrap <fqdn>:<port>
      ```

## Expected Behavior
The cluster will come up and all of the nodes will behave appropriately.

## Possible Solution
Not even sure. Evidently a file is not being found, but I am not sure which one, as I have verified the path of each file existing on each system.

## Context (Environment)
I am attempting to bring up a cluster of qdrant databases and have them communicating with each other. This is being deployed on a set of bare-metal Fedora 42 systems (vms).

**Comment by larrydewey** [comment]
Turns out I had some keys incorrect under the tls setting. My mistake!

**Comment by timvisee** [comment]
For others that might land on this issue, the problem was in the way the certificates were configured.

```yaml
tls:
    cert_file: "/etc/pki/tls/qdrant/qdrant.crt"
    key_file: "/etc/pki/tls/qdrant/qdrant-key.pem"
    cert_ttl: 3600
```

should be:

```yaml
tls:
    cert: "/etc/pki/tls/qdrant/qdrant.crt"
    key: "/etc/pki/tls/qdrant/qdrant-key.pem"
    cert_ttl: 3600
```

Find more documentation [here](https://qdrant.tech/documentation/guides/security/#tls).
