### ISSUE TITLE
 Failed to send message: Failed to send message: Tonic error

### ISSUE THREAD

**Issue by dingusagar** [qdrant/qdrant#992]
I was trying to run qdrant in distributed mode via multiple containers in the same machine for testing. But I am getting this error saying failed to send message.  Could someone help what I am doing wrong here. 

```
[15:19:28] ➜  docker-compose up first-peer 
Creating network "qdrant-volumne_qdrant" with the default driver
Creating qdrant-volumne_first-peer_1 ... done
Attaching to qdrant-volumne_first-peer_1
first-peer_1   |            _                 _    
first-peer_1   |   __ _  __| |_ __ __ _ _ __ | |_  
first-peer_1   |  / _` |/ _` | '__/ _` | '_ \| __| 
first-peer_1   | | (_| | (_| | | | (_| | | | | |_  
first-peer_1   |  \__, |\__,_|_|  \__,_|_| |_|\__| 
first-peer_1   |     |_|                           
first-peer_1   | 
first-peer_1   | Access web UI at https://ui.qdrant.tech/?v=v0.9.1
first-peer_1   | 
first-peer_1   | [2022-09-06T09:49:33.338Z INFO  storage::content_manager::consensus::persistent] Initializing new raft state at ./storage/raft_state
first-peer_1   | [2022-09-06T09:49:35.370Z INFO  qdrant::consensus] With current tick period of 100ms, leader will be established in approximately 4000ms. To avoid rejected operations - add peers and submit operations only after this period.
first-peer_1   | [2022-09-06T09:49:35.475Z INFO  raft::raw_node] RawNode created with id 1943720206961485249., raft_id: 1943720206961485249, id: 1943720206961485249
first-peer_1   | [2022-09-06T09:49:35.478Z INFO  qdrant::tonic] Qdrant gRPC listening on 6334
first-peer_1   | [2022-09-06T09:49:35.496Z INFO  actix_server::builder] Starting 15 workers
first-peer_1   | [2022-09-06T09:49:35.496Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
first-peer_1   | [2022-09-06T09:49:49.734Z WARN  qdrant::consensus] Failed to send message: Failed to send message: Tonic error: transport error: transport error: error trying to connect: tcp connect error: Connection refused (os error 111): tcp connect error: Connection refused (os error 111): Connection refused (os error 111)
first-peer_1   | [2022-09-06T09:49:49.834Z WARN  qdrant::consensus] Failed to send message: Failed to send message: Tonic error: transport error: transport error: error trying to connect: tcp connect error: Connection refused (os error 111): tcp connect error: Connection refused (os error 111): Connection refused (os error 111)
```
```
[15:19:19] ➜ docker-compose up second-peer
qdrant-volumne_first-peer_1 is up-to-date
Creating qdrant-volumne_second-peer_1 ... done
Attaching to qdrant-volumne_second-peer_1
second-peer_1  |            _                 _    
second-peer_1  |   __ _  __| |_ __ __ _ _ __ | |_  
second-peer_1  |  / _` |/ _` | '__/ _` | '_ \| __| 
second-peer_1  | | (_| | (_| | | | (_| | | | | |_  
second-peer_1  |  \__, |\__,_|_|  \__,_|_| |_|\__| 
second-peer_1  |     |_|                           
second-peer_1  | 
second-peer_1  | Access web UI at https://ui.qdrant.tech/?v=v0.9.1
second-peer_1  | 
second-peer_1  | [2022-09-06T09:49:47.172Z INFO  storage::content_manager::consensus::persistent] Initializing new raft state at ./storage/raft_state
second-peer_1  | [2022-09-06T09:49:49.902Z INFO  raft::raw_node] RawNode created with id 10272493160997323134., raft_id: 10272493160997323134, id: 10272493160997323134
second-peer_1  | [2022-09-06T09:49:49.905Z INFO  qdrant::tonic] Qdrant gRPC listening on 6334
second-peer_1  | [2022-09-06T09:49:49.924Z INFO  actix_server::builder] Starting 15 workers
second-peer_1  | [2022-09-06T09:49:49.924Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
second-peer_1  | [2022-09-06T09:49:50.666Z WARN  storage::content_manager::consensus::persistent] Replaced address of peer 10272493160997323134 from http://172.69.2.6:6335/ to http://172.69.2.6:6335/

```

Docker compose file looks like this. 
```yaml
version: "3.9"
networks:
  qdrant:
    ipam:
      config:
        - subnet: 172.69.2.0/24
services:
  first-peer:
    image: qdrant/qdrant:v0.9.1
    command: ./qdrant --uri 'http://172.69.2.5:6335'
    networks:
      qdrant:
        ipv4_address: 172.69.2.5
    ports:
      - "6333:6333"
      - "6334:6334"
      

    environment:
      - RUST_BACKTRACE=full
      - QDRANT__CLUSTER__ENABLED=true
    volumes:
      - ./config:/qdrant/config/
      - ./node1:/qdrant/storage
    
  second-peer:
    image: qdrant/qdrant:v0.9.1
    command: ./qdrant --bootstrap 'http://172.69.2.5:6335' 
    networks:
      qdrant:
        ipv4_address: 172.69.2.6
    
    volumes:
      - ./config:/qdrant/config/
      - ./node2:/qdrant/storage
    depends_on:
      - first-peer
    links: 
      - first-peer  
    environment:
      - RUST_BACKTRACE=full
      - QDRANT__CLUSTER__ENABLED=true
    restart: unless-stopped  
```
